### ISSUE TITLE
гамно

### ISSUE THREAD

**Issue by Nifacy** [yuweebix/microfrontend#1]
гаумноу

**Comment by yuweebix** [comment]
not relevant, nor helpful. closed.

**Comment by yuweebix** [comment]
а не, реально.

**Comment by yuweebix** [comment]
или? вообщем нет.

**Comment by Nifacy** [comment]
sorry, but i think that this issue is нужно кароча необходимо для данного проекта (я английский не знаю аааааааааааааааааа)

**Comment by Nifacy** [comment]
ОТКРОЙ!!!!

**Comment by yuweebix** [comment]
нет

**Comment by Nifacy** [comment]
:((((((((((((((((((((((((((

**Comment by yuweebix** [comment]
иди в свои гамноупитоны

**Comment by Nifacy** [comment]
все давай пока .
